name: Alerta lluvia autom√°tica

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-alerta:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: |
          python lluvia.py
          python alerta.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEATHERLINK_API_KEY: ${{ secrets.WEATHERLINK_API_KEY }}
          WEATHERLINK_API_SECRET: ${{ secrets.WEATHERLINK_API_SECRET }}
